// Generated by https://quicktype.io

//copiar respuesta del api
// ctrl + shif +p -> paste json to code

export interface PokeResponse {
  count: number;
  next: string;
  previous: null;
  results: Result[];
}

export interface Result {
  name: string;
  url: string;
}
